### PR TITLE
Improve storage: Retrieve and count objects

### PR DESCRIPTION
**Pull request by iAdamo**
Updated DBStorage and FileStorage, adding two new methods:
  - A method to retrieve one object.
  - A method to count the number of objects in storage.

Updated test_db_storage and test_file_storage, adding two new tests

### CODE REVIEW

**Comment by the1Riddle** [comment]
for someone to merge your pull request you must add them as a collaborator

**Comment by iAdamo** [comment]
Yeah, I knew that. I was wondering why they would specify us to ask for a
peer when we already had a partner for it.

**Comment by iAdamo** [comment]
Nice to meet you Elvis. Let's meet up somewhere else? Whatsapp
+2349139290549

**Comment by the1Riddle** [comment]
> Yeah, I knew that. I was wondering why they would specify us to ask for a peer when we already had a partner for it.

Actually that was not a must

**Comment by the1Riddle** [comment]
> Nice to meet you Elvis. Let's meet up somewhere else? Whatsapp +2349139290549

sure, no problem.

**Pull request merged**
